### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral-cli#5]
- [x] remove decorators legacy stuff
- [ ] allow to have empty view choise
- [x] use new models exposed at `cerebral/models`

**Comment by Guria** [comment]
@christianalfoni scaffolding doesn't work well when using None as view

**Comment by christianalfoni** [comment]
What is not working?

**Comment by Guria** [comment]
it doesn't copies shared stuff and rest like git init and npm install

**Comment by bfitch** [comment]
Yup need to look into this
